### ISSUE TITLE
created model file not in the right location.

### ISSUE THREAD

**Issue by singleseeker** [bxqm/dart_data_class_generator#30]
Using Create Data Classes Based on JSON command, the files  just in the root folder.

hope these files just in the same path with the raw JSON file.

**Comment by bnxm** [comment]
Does it still happen with version 0.4.3 as I cannot reproduce this ?

**Comment by singleseeker** [comment]
![2020-11-12 01 09 32](https://user-images.githubusercontent.com/520698/98842326-58db9280-2484-11eb-8763-442057cc52d3.gif)

Both 0.44 and 0.43 dit not work.

**Comment by bnxm** [comment]
Huh, ok thanks. Its probably platform related as for me on windows its working. I can try to fix that in the next release.

**Comment by singleseeker** [comment]
wow, cool, can not wait for it!

**Comment by tnarik** [comment]
The problem is that the extension is using a windows path separator, instead of an OS dependent path separator.

It should be using `path.delimiter` (and disambiguate 'path', which is both a library and a local variable), or better yet a combination of `path.parse` and path split based on the OS separator.

**Comment by tnarik** [comment]
The problem is that the extension is using a windows path separator, instead of an OS dependent path separator.

It should be using `path.delimiter` (and disambiguate 'path', which is both a library and a local variable), or better yet a combination of `path.parse` and path split based on the OS separator.
